### ISSUE TITLE
Adding a filter hook for data sent to Paypal

### ISSUE THREAD

**Issue by fueledbycolab** [eventespresso/eea-payment-methods-pro#1]
Trying to get event name (and possibly additional data at a later date) to pass into Paypal dashboard. We attempted to modify the gateway code directly (a no-no, I realize) to no avail. After submitting a post to your Community Forum, Josh suggested I submit an issue here to request working with you to add a filter hook to send custom data to Paypal. Can you help? Many thanks!

**Comment by tn3rb** [comment]
which PayPal payment method are you using?

 * PayPal Standard (deprecated)
 * PayPal Express (replaces Standard)
 * PayPal Pro 

???

**Comment by fueledbycolab** [comment]
Ah, sorry for the lack of detail. Paypal Payflow Pro. And, a link to the [original question](https://eventespresso.com/topic/payment-gateway-customization/)

**Comment by tn3rb** [comment]
okay I added a filter in \EEG_Payflow_Pro_Onsite::do_direct_payment() just before the try catch block so that you can add/edit/delete/mangle the ` $payment_request_args ` variable.

Is that where you what you were trying to edit before?

Branch has been sent for review, and will probably get merged soon.

(internal use: plz see: https://events.codebasehq.com/projects/event-espresso/tickets/10431)

**Comment by fueledbycolab** [comment]
Yes, we were attempting to get the event name passed in the Description field at a minimum. Thanks and I'll be on the lookout for the merge!

**Comment by tn3rb** [comment]
we can notify you here when that happens

**Comment by tn3rb** [comment]
Sending the work done for this issue for testing, but as an FYI, according to Michael, who is the mastermind behind our gateways, the following methods:

- EE_Gateway::_format_order_description()
- EE_Gateway::_format_line_item_name()
- EE_Gateway::_format_line_item_desc()
- EE_Gateway::_format_* (etc, etc)

which this gateway now uses, are filterable (and standardized).
So to add the Event name to the order's description you would do something like:

```php
        add_filter(
            'FHEE__EE_Gateway___order_description',
            function ($order_description, \EE_Gateway $gateway_class, \EE_Payment $payment) {
                $transaction = $payment->transaction();
                if ( ! $transaction instanceof \EE_Transaction) {
                    return $order_description;
                }
                $registration = $transaction->primary_registration();
                if ( ! $registration instanceof \EE_Registration) {
                    return $order_description;
                }
                $event_name = $registration->event_name();
                return "{$order_description} for event {$event_name}";
            },
            10,
            2
        );
```

I'll still notify you when the other filter gets added to master, since it allows access to all of the payment request args.

**Comment by mnelson4** [comment]
yeah that's what the case SHOULD be @tn3rb; but unfortunately the order description is actually currently not filterable, because it doesn't use `EE_Gateway::_format_order_description()` like it should. So that's also getting added to the gateway atm

**Comment by tn3rb** [comment]
ahhh kk I misread your comment to me in the ticket then.

**Comment by fueledbycolab** [comment]
hi, any updates on the merge of this feature? wanting to make sure I didn't miss any notification(s)...

**Comment by mnelson4** [comment]
oh, thanks for checking. Yes this got merged into PayFlow 1.0.4

**Comment by fueledbycolab** [comment]
Great, thanks for the update. Do you have a ballpark release date yet?

**Comment by mnelson4** [comment]
like today or tomorrow. @Pebblo is working on it at the moment

**Comment by Pebblo** [comment]
Hi there,

Payflow 1.0.4 has now been released.

**Comment by fueledbycolab** [comment]
Great, thanks. Does the "add_filter" code above still apply to our desired solution of adding event name to the Description field?

**Comment by mnelson4** [comment]
yes @tn3rb's code snippet from above should now work with PayPal Payflow as well.

**Comment by Pebblo** [comment]
Just to note the filter Brent provided will still work, however the default description for the PayPlow payment method is now:

`Event Registrations from {site name} for {event}`

So depending on the information you want to add you may not need to use the filter currently.

**Comment by fueledbycolab** [comment]
Thanks for the clarification @Pebblo
